### ISSUE TITLE
Great idea, but why GPL?

### ISSUE THREAD

**Issue by seanfcarroll** [AshampooSystems/boden#1]
Wouldn't MIT lead to more adoption.

It's a great idea for cross-platform apps, good 'ol C++ !

**Comment by haneefmubarak** [comment]
I second that as a library, it should probably be distributed as MIT licensed.

For what it's worth, [you CANNOT distribute GPL code on the app store](https://www.fsf.org/news/2010-05-app-store-compliance).

**Comment by Mk-Chan** [comment]
I suppose LGPL is an alternative. That should bypass their filter since it doesn't force the app to be GPL as well.

**Comment by Calinou** [comment]
> For what it's worth, you CANNOT distribute GPL code on the app store.

It's possible to add an exception to the license (as permitted by the GPL) to allow distribution on the Apple App Store.

**Comment by haukeduden** [comment]
We’re still in the process of figuring out what the right open-source licensing model for Boden should be. In the long run, development must be financed by a viable business model as Boden is not a hobby project. We’re considering adding a commercial option later, ending up with a dual GPL/commercial license similar to other projects. We’re happy to hear your thoughts about other licensing options!

**Comment by seanfcarroll** [comment]
If you want people to contribute to the codebase, then I would license it at MIT, especially as the Apple app store is not accepting GPL.

If it is to be a commercial product, then I would close source it and look for outside financing.

A third option is to keep it open source, and then charge for services / support / training.

Our of interest, how do you recommend dealing with on-app storage? Core Data via APIs or roll your own?

**Comment by haneefmubarak** [comment]
I think @seanfcarroll is on to the right idea here, especially with regards to:

 > A third option is to keep it open source, and then charge for services / support / training.

A good example of this is [NodeSource](https://nodesource.com/), who [sell support for NodeJS](https://nodesource.com/services/support) and are large contributors to that project.

Another even more well known and near universally used example of this is [SQLite](https://www.sqlite.org/index.html) who do rather well offering [their support services and specialized extensions](https://www.sqlite.org/prosupport.html).

---

@seanfcarroll I'm not a project dev — just a passerby, but I imagine that using something like SQLite is fair game just because it works on basically anything and everything. Core Data does give you the convenience of a prebuilt object graph framework, but then you need to do something different on Android, which IMHO rather defeats the point of trying to build from a unified codebase.

**Comment by Calinou** [comment]
> 2. If it is to be a commercial product, then I would close source it and look for outside financing.

I would really advise not going the proprietary route, as it's entirely possible to make a profit with open source software.

**Comment by webfolderio** [comment]
Don't change the license, GPL is fine. If someone wants to develop serious app. they should buy commercial license to support project.

> A third option is to keep it open source, and then charge for services / support / training.

I made a similar mistake and prefer to use MIT license to my product. Nobody bought support or training package. I sold my first license when i replace the MIT license with GPL.

Developers don't understand that how is difficult to maintain open source project.

**Comment by haneefmubarak** [comment]
@webfolderio the challenge is that _even_ if someone develops an app and open sources it under the GPL, they still can't publish it on the Apple App Store, which makes it effectively useless (the purpose of the library is to enable single codebases for both iOS and Android apps).

If you simply add a clause that allows usage on the App Store specifically, you're making the issue of [license proliferation](https://en.wikipedia.org/wiki/License_proliferation) even worse, because you basically just cooked up your own "similar-to-the-GPL-but-with-this-one-exception" license.

---

Also, @webfolderio just as an aside, IANAL, but assuming that the project you are talking about is cdp4j, you seriously need to have an attorney review your licensing scheme, because while your README and website state that a commercial license is required in order to use the software, the actual included license file in the repository is in essence a badly-modified MIT license. As a result, almost any sane court in any sane jurisdiction would probably treat the software as simply being the equivalent of being MIT-licensed for any and all intents and purposes, on the basis that the actual license file supersedes and overrides any kind of notice elsewhere given industry norms. Furthermore, a court is not likely to take kindly to a haphazardly modified or rewritten license either, because clarity and comprehensiveness are paramount — there's a reason as to why most proprietary software licenses are remarkably long (and even the GPL or the Apache license families, while being open source licenses, are also quite long).

**Comment by Calinou** [comment]
> If you simply add a clause that allows usage on the App Store specifically, you're making the issue of license proliferation even worse, because you basically just cooked up your own "similar-to-the-GPL-but-with-this-one-exception" license.

GPL exceptions can be removed at any time, so I'm not sure if it's really license proliferation as it doesn't cause incompabilities.

**Comment by haneefmubarak** [comment]
It's not necessarily that there may be an incompatibility as much as it's now yet-another-thing that needs to be reviewed by a given user. Additionally, this package is 50% unusable if you can't put an app you make on the Apple App Store, which to a great extent obviates the usage of the package at all; indeed, removing the exception is not a practicable argument because the whole thing loses use without such an exception.

If ensuring that no one "runs off with the code without paying" is a particularly important goal, using an appropriate license such as the MPL may be more appropriate. Users would be free to use the library exactly-as-is-without-any-modifications-whatsoever to build their apps for the Apple App Store, but they would not be able to alter or import+change the library code in any useful way without contributing the changes back. 

Once again, IANAL, but I don't think the LGPL would be viable either because their exists no normal mechanism for a user to relink an installed iOS app against their own version of a library, thus presenting basically the same problem as does the GPL.

**Comment by afonari** [comment]
fdroid store will gladly accept GPL.

**Comment by gitoby** [comment]
A short update on this as it was again discussed on HN (https://news.ycombinator.com/item?id=20050345) lately.

We are currently working on adding an LGPL licensing option to resolve the issues with the GPL. Our proposal is currently being reviewed by our lawyers. We expect that the LGPL option will land within the next weeks. We'll keep you updated.

**Comment by gitoby** [comment]
We added LGPL in the v0.2 release.
